DROP TABLE IF EXISTS app_user;
CREATE TABLE app_user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
    birthday DATETIME DEFAULT CURRENT_TIMESTAMP,
    picture LONGBLOB
);